on: push
name: on push
jobs:
  gitHubActionForPylint:
    name: GitHub Action for pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: GitHub Action for pylint
        uses: pip install -r requirements.txt ; pylint **/*.py
